"""
Remove the ASR results for the single-word tests. [Generated by Gemini.]

This script maps the relationship from audio_asr -> audio_results 
-> audio_trials to find all ASR records associated with the 
cnc, win, or nu6 projects. It then updates those the ASR data fields to be 
an empty string ("").

It includes a dry-run mode that defaults to True. There is a small 
check to the SQL queries (AND aa.data != '') so it only flags or updates rows 
that actually need changing, saving you from processing rows that are already 
empty.
"""
import sqlite3
import sys
from absl import app
from absl import flags

def print_asr_data_counts(cursor: sqlite3.Cursor):
    """
    Queries the database to count the number of empty and non-empty 'data' 
    fields in the audio_asr table, grouped and sorted by project name.
    """
    query = """
        SELECT 
            at.project,
            SUM(CASE WHEN IFNULL(aa.data, '') = '' THEN 1 ELSE 0 END) as empty_count,
            SUM(CASE WHEN IFNULL(aa.data, '') != '' THEN 1 ELSE 0 END) as non_empty_count
        FROM audio_asr aa
        JOIN audio_results ar ON aa.ref = ar.id
        JOIN audio_trials at ON ar.trial = at.id
        GROUP BY at.project
        ORDER BY at.project;
    """
    
    try:
        cursor.execute(query)
        results = cursor.fetchall()
        
        print("\n=== ASR Data Completeness by Project ===")
        print(f"{'Project':<15} | {'Empty (Needs ASR)':<18} | {'Non-Empty (Completed)'}")
        print("-" * 58)
        
        if not results:
            print("No data found to aggregate.")
            return
            
        for project, empty_count, non_empty_count in results:
            # project might be None if the database has orphaned records, fallback to 'UNKNOWN'
            safe_project = project if project else "UNKNOWN"
            print(f"{safe_project:<15} | {empty_count:<18} | {non_empty_count}")
            
        print("-" * 58)
        
    except sqlite3.Error as e:
        print(f"Error executing count query: {e}")


# Define command-line flags
FLAGS = flags.FLAGS
flags.DEFINE_boolean('dry_run', True, 
                     'If True, prints rows that would be updated. If False, performs the actual update.')
try:
    flags.DEFINE_string('dbfile', 'experiments_malcolm.db', 
                        'Path to the SQLite database file.')
except flags.DuplicateFlagError:
    pass # Flag was already defined by another module during pytest collection
flags.DEFINE_string('word', '%', 
                    'The word to target for clearing ASR data. Use % for all words, or specify a single word.')

def main(argv):
    del argv  # Unused, but required by absl.app

    print(f"Connecting to database: {FLAGS.dbfile}")
    
    try:
        conn = sqlite3.connect(FLAGS.dbfile)
        cursor = conn.cursor()
    except sqlite3.Error as e:
        print(f"Failed to connect to database: {e}")
        sys.exit(1)

    print_asr_data_counts(cursor)  # Show the current state of ASR data before any changes

    try:
        # Define the target projects
        target_projects = ('cnc', 'win', 'nu6')
        # Create a parameterized string for the IN clause based on the tuple length
        placeholders = ', '.join(['?'] * len(target_projects))

        if FLAGS.dry_run:
            # --- DRY RUN LOGIC ---
            print("\n=== DRY RUN MODE ACTIVATED ===")
            print(f"Checking for ASR data linked to projects: {target_projects}")
            
            # Select rows that WOULD be modified (ignoring ones that are already empty)
            select_query = f"""
                SELECT aa.ref, at.project, aa.data
                FROM audio_asr aa
                JOIN audio_results ar ON aa.ref = ar.id
                JOIN audio_trials at ON ar.trial = at.id
                WHERE at.project IN ({placeholders})
                  AND LOWER(at.answer) LIKE '{FLAGS.word.lower()}'
                  AND IFNULL(aa.data, ' ') != '';
            """
            cursor.execute(select_query, target_projects)
            rows = cursor.fetchall()
            
            if rows:
                print("\nThe following rows in 'audio_asr' WOULD have their data cleared:\n")
                for row in rows:
                    # Truncating the printed ASR data so it doesn't flood your terminal if it's long
                    preview_data = (row[2][:50] + '...') if row[2] and len(row[2]) > 50 else row[2]
                    print(f"ASR Ref ID: {row[0]} | Project: '{row[1]}' | Current Data: '{preview_data}'")
                
                print(f"\nTotal rows that would be updated: {len(rows)}")
                print("To execute the actual update, run the script with: --nodry_run")
            else:
                print("\nNo rows found that need updating. All target ASR data is already empty.")

        else:
            # --- ACTUAL UPDATE LOGIC ---
            print("\n=== EXECUTION MODE ACTIVATED ===")
            print(f"Updating ASR data for projects: {target_projects}")
            
            # Update the data to an empty string
            update_query = f"""
                UPDATE audio_asr
                SET data = ''
                WHERE ref IN (
                    SELECT ar.id
                    FROM audio_results ar
                    JOIN audio_trials at ON ar.trial = at.id
                    WHERE at.project IN ({placeholders})
                      AND LOWER(at.answer) LIKE '{FLAGS.word.lower()}'
                )
                AND IFNULL(data, ' ') != '';
            """
            cursor.execute(update_query, target_projects)
            updated_rows = cursor.rowcount
            
            # Commit the changes
            conn.commit()
            print(f"Successfully cleared the 'data' field for {updated_rows} row(s) in the 'audio_asr' table.")

    except sqlite3.Error as e:
        print(f"A database error occurred: {e}")
        conn.rollback() # Protect the database on failure
        
    finally:
        conn.close()

if __name__ == "__main__":
    app.run(main)
