# Summarize the results from the run_exp1d.sh script by parsing the 
# analysis.txt files and plotting CNC and Win correct vs. OOV penalty.
# Generated by Gemini: https://gemini.google.com/share/354108138ea4

import os
import glob
import re
import matplotlib.pyplot as plt
import numpy as np

from absl import app
from absl import flags
from absl import logging

# Define command line flags
FLAGS = flags.FLAGS
flags.DEFINE_string('base_dir', 'exp1', 'Base directory containing the experiment folders.')
# Replace XXX wth test-type.
flags.DEFINE_string('output_plot', 'summary_XXX_plot.png', 'Filename to save the generated plot.')
flags.DEFINE_enum('test_type', {'forced', 'exact'}, 'forced', 'Type of test to summarize.')

def parse_metrics(filepath):
    """Parses the last 8 lines of the file to find 'cnc' and 'win' values."""
    cnc_val = None
    win_val = None
    
    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            
        # Focus only on the last 8 lines
        last_lines = lines[-8:] if len(lines) >= 8 else lines
        text_to_search = " ".join(last_lines).lower()
        
        # Regex to find 'cnc' and 'win' followed by =, :, or just spaces, then a number
        # Example matches: "cnc: 45.2", "win = 10", "cnc 0.5"
        cnc_match = re.search(r'cnc[^\d]*([-+]?\d*\.?\d+)', text_to_search)
        win_match = re.search(r'win[^\d]*([-+]?\d*\.?\d+)', text_to_search)
        
        if cnc_match:
            cnc_val = float(cnc_match.group(1))
        if win_match:
            win_val = float(win_match.group(1))
            
    except Exception as e:
        logging.error(f"Error reading {filepath}: {e}")
        
    return cnc_val, win_val

def main(argv):
    # Unused args
    del argv

    # Glob pattern to match files like exp1/exp1_forced_XXX_results/analysis.txt
    search_pattern = os.path.join(FLAGS.base_dir, 
                                  f'*_{FLAGS.test_type}_*_results',
                                  'analysis.txt')
    file_list = glob.glob(search_pattern)
    
    if not file_list:
        logging.warning(f"No files found matching pattern: {search_pattern}")
        return

    data = []

    # Regex to extract the OOV penalty (XXX) from the directory name
    # It looks for '_{test_type}_', captures any integer (including negative), followed by '_results'
    dir_regex = re.compile(rf'_{FLAGS.test_type}_(-?\d+)_results')

    for filepath in file_list:
        match = dir_regex.search(filepath)
        if not match:
            logging.info(f"Could not extract OOV penalty from {filepath}, skipping.")
            continue
            
        oov_penalty = int(match.group(1))
        cnc, win = parse_metrics(filepath)
        
        if cnc is not None and win is not None:
            data.append((oov_penalty, cnc, win))
        else:
            logging.warning(f"Missing 'cnc' or 'win' in {filepath}")

    if not data:
        logging.error("No valid data extracted. Exiting.")
        return

    # Sort data primarily by OOV penalty so the line plot connects points correctly
    data.sort(key=lambda x: x[0])
    
    # Unzip the sorted data into separate lists for plotting
    oov_penalties, cnc_values, win_values = zip(*data)

    # Create the plot
    fig, ax = plt.subplots(layout='constrained')
    x = np.arange(len(oov_penalties))  # Use index for x-axis to ensure proper spacing
    width = 0.35  # Width of the bars 
    # Plot CNC and Win on the same graph
    rects = ax.bar(x - width/2, cnc_values, width=width, label='CNC', color='blue')
    ax.bar_label(rects, padding=3)
    rects = ax.bar(x + width/2, win_values, width=width, label='Win', color='orange')
    ax.bar_label(rects, padding=3)
    
    ax.set_title('Single Word Correct vs. OOV Penalty')
    ax.set_xticks(x, oov_penalties)

    ax.set_xlabel('OOV Penalty')
    ax.set_ylabel('Words Correct (%)')
    ax.legend(ncols=2)
    
    # Save and optionally show the plot
    # plt.tight_layout()
    output_filename = FLAGS.output_plot.replace('XXX', FLAGS.test_type) 
    plt.savefig(output_filename)
    logging.info(f"Plot saved successfully to {output_filename}")
    plt.show()

if __name__ == '__main__':
    app.run(main)
