[uwsgi]
module = wsgi
master = true

# Also specified 4 places in nginx config
socket = /tmp/audio.experiments.api.sock
chmod-socket = 666
vacuum = true
die-on-term = true

chdir = %d
module = server:app
processes = 4
threads = 2
# Increase buffer size to handle Safari's huge request headers
buffer-size = 8192
#stats = 127.0.0.1:9191

env = SELECTED_DATABASE=/var/www/jnd.emily/experiments.db
# Need to revisit review selection assignment to find out why some have 7 reviewers and some have 0
env = CAP_COMPLETED_PATIENT_PROJECTS=0